### ISSUE TITLE
Mais descrição do projeto e incremento do HTML.

### ISSUE THREAD

**Issue by matheusgr** [carolvalenca/devweb#1]
Podes colocar uma descrição melhor das telas do projeto? Especialmente, é importante ter uma ideia de como serão os componentes da tela principal e como será o componetne de maior interatividade.

Talvez vc tenha um componente de livro que tenha um slide... e ao mover o slide vc vê uma cena ou uma descrição resumida da parte do livro (sem spoiler) e isso afeta a marcação do livro atual bem como tua taxa de leitura média e/ou a quantidade de livros lidos na tela principal.

**Comment by carolvalenca** [comment]
Sim, eu pensei nisso de criar uma página de detalhamentos do livro com título, autor e sinopse, e pra mostrar também justamente algumas estatísticas da leitura e tals, detalhei melhor agora no readme!
