### ISSUE TITLE
Sugestão de funcionalidade

### ISSUE THREAD

**Issue by RaylaMedeiros** [carolvalenca/devweb#4]
Acho que uma funcionalidade legal seria poder adicionar livros que a pessoa pretende ler, pra poder já planejar suas próximas leituras.

**Comment by DiegoGamaV** [comment]
Acho que outra bem legal e simples de adicionar seria a de um outro estado para leituras: **abandonado**. Tem duas opções de implementar ao meu ver:
1. Ocorre automaticamente, a partir de X dias com a leitura **em progresso**, porém com a porcentagem sem ter mudado
2. Ou manualmente, onde é possível marcar uma leitura como abandonada e ela fica "arquivada" fora dos filtros comuns, mas acessível através de um filtro especial de leituras abandonadas.

E aí pode ser que você queira que já seja possível avaliar a leitura ou ter um campo de comentário do porquê ela foi abandonada.
