### ISSUE TITLE
Duplo setBooksFiltered

### ISSUE THREAD

**Issue by lucasalustiano** [carolvalenca/devweb#8]
Oi, [aqui](https://github.com/carolvalenca/devweb/blob/b279823b975ce925c9ac774a0045864578f0383e/frontend/src/pages/Main/index.js#L13) tem dois setBooksFiltered. Algum motivo específico pra isso?

**Comment by adrianora** [comment]
De fato acredito que esteja redundante, porque no momento que a página for renderizada pela primeira vez, tanto o books quanto booksFiltered serão carregados com valor vazio, então o switch case já garante que o filtro será zerado no momento apropriado.

**Comment by carolvalenca** [comment]
Nem tinha percebido isso na real, acabei de consertar!
