### ISSUE TITLE
Tornar label mais semântico com o campo Input

### ISSUE THREAD

**Issue by adrianora** [carolvalenca/devweb#9]
Ao invés de parágrafo no componente [Input](https://github.com/carolvalenca/devweb/blob/main/frontend/src/components/Input/index.js), o nome do campo pode ser usado diretamente com label do HTML, o gera uma semântica ao relacionar labels com os campos inputs. 

Um exemplo prático pode ser visto nesse link: https://www.w3schools.com/tags/tag_input.asp

**Comment by carolvalenca** [comment]
Verdade, vou modificar isso!
